server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 88
    connection-timeout: 5000
    context-path: /

spring:
    profiles:
        active: dev
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 127.0.0.1
        port: 6379
        password: redhat      # 密码（默认为空）
        timeout: 15000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    mvc:
        dateFormat: yyyy-MM-dd HH:mm  # 配置日期转换格式

# Mybatis配置
mybatis:
   type-aliases-package: cn.hejinyo
   mapper-locations: classpath*:cn/hejinyo/**/dao/*Dao.xml

# 线程池配置
corePoolSize: 40
maximumPoolSize: 40
keepActiveTime: 200